name: Static Analysis

on:
  pull_request:
  push:
    branches: [main]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:

    # https://github.com/actions/setup-python
    - name: Install Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install black
        pip install flake8
        pip install isort
        pip install pre-commit

    # https://github.com/actions/checkout
    - name: Checkout cc-legal-tools-app
      uses: actions/checkout@v4
      with:
        path: cc-legal-tools-app

    - name: pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
      working-directory: ./cc-legal-tools-app
